name: release
on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Lint
      run: npm run lint

    - name: Start databases
      run: docker-compose up -d

    - name: Wait for databases to be available
      run: sleep 10

    - name: Test
      run: npm test

    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Stop databases
      run: docker-compose down
