name: test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
          - 20.x
        mssql-version:
          - ^7.0.0
          - ^8.0.0

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Install mssql
        run: npm install --no-save mssql@${{ matrix.mssql-version }}

      - name: Lint
        run: npm run lint

      - name: Start databases
        run: docker-compose up -d

      - name: Wait for databases to be available
        run: sleep 10

      - name: Test
        run: npm run cover

      - name: Stop databases
        run: docker-compose down

      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
